baseURL = "https://bytecolony.computer/"
languageCode = "en-us"
title = "Byte Colony"

[markup.goldmark.renderer]
  unsafe = true
  hardWraps = true

[markup.highlight]
  codeFences = true
  noClasses = false
  lineNos = false

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[sitemap]
  changeFreq = "weekly"
  priority = 0.5

[params]
  tagline = "a journey underground"
  pitch   = "My adventure underground as I feed my interest in computers!"
  github  = "https://github.com/ekansh38"
  youtube = "https://www.youtube.com/@byte_colony"
  itchio  = "https://byte-colony.itch.io/"
  email   = "ekansh@ekanshgoenka.com"
